### PR TITLE
install build directory using setup.py in original source tree

### PR DESCRIPTION
**Pull request by k-okada**
a patch not to pollute src directory, @garaemon could you check if this is ok, I think we can remove setup.py from ros rtshell/rtctree/rtsprofile direcotry, but not sure.
@130s, I'm not sure if it works with other tools that depends on rtshell ,such as rtmlaunch

### CODE REVIEW

**Comment by 130s** [comment]
+1

Although I won't have time to actually test until Friday at latest, this makes sense; Looking at [rtshell upstream repo](https://github.com/gbiggs/rtshell/tree/master/rtshell), most or all python files might look like `scripts`, not `modules`. So `setup.py` might not be necessary.

**Comment by garaemon** [comment]
+1

I confirmed rtmlaunch works by `rtmlaunch hrpsys_gazebo_tutorials hrp2jsknt_hrpsys_bringup.launch`.

However, we still download rtshell source code into src directory. Is it another issue?

```
~/ros_catkin_ws_release/hydro/src/rtm-ros-robotics/openrtm_common/rtshell_core(branch:k-okada-install_build_direcotory*) » git status --ignored
# On branch k-okada-install_build_direcotory
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       rtshell/installed
# Ignored files:
#   (use "git add -f <file>..." to include in what will be committed)
#
#       rtshell/build/
nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by k-okada** [comment]
please be careful when we test this branch, usually users use .bashrc to set custom PYTHONPATH to enable loading python libs, for example I need following commit [1] to run rtls, without this rtls fails with import RTC as [2].

I'll wait isaac's confirmation.

[1] https://github.com/k-okada/rtshell_core/commit/1a72bb70191035bc1006652578249155b265133b

[2] https://travis-ci.org/start-jsk/rtshell_core/builds/18718222

**Comment by k-okada** [comment]
> However, we still download rtshell source code into src directory. Is it another issue?

no, just forget. I just commited.

**Comment by garaemon** [comment]
> > However, we still download rtshell source code into src directory. Is it another issue?
> 
> no, just forget. I just commited.

if we download source code under build directory, it may break build sequence of the packages which use rtshell_core programs during its compilation.

For example, if we download hrpsys source code under build directory, the packages which uses hrpsys-base such as hrpsys_gazebo_general, may fail to compile.

Is there any package which uses rtshell_core during its compilation?
We need to confirm those packages can be built correctly.

**Comment by k-okada** [comment]
> We need to confirm those packages can be built correctly.

sorry I merged this pull request without confirm. so I'll leave this PR open.

**Comment by 130s** [comment]
I tested https://github.com/k-okada/rtshell_core/commit/9e33cfce20cdb47c2880f4fe888daec7bb34ffda and yet couldn't `rosrun rtshell rtls`.

`.bashrc` being disabled,

```
$ cd %CATKINWS%
$ source install/setup.bash
$ rosrun rtshell rtls
[rosrun] Couldn't find executable named rtls below /home/uss/cws_proof/install/share/rtshell
$ env | grep ROS
ROS_ROOT=/opt/ros/hydro/share/ros
ROS_PACKAGE_PATH=/home/uss/cws_proof/install/share:/home/uss/cws_proof/install/stacks:/opt/ros/hydro/share:/opt/ros/hydro/stacks
ROS_MASTER_URI=http://localhost:11311
LD_LIBRARY_PATH=/home/uss/cws_proof/install/lib:/opt/ros/hydro/lib
CPATH=/home/uss/cws_proof/install/include:/opt/ros/hydro/include
PATH=/home/uss/cws_proof/install/bin:/opt/ros/hydro/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/uss/cws_proof
ROSLISP_PACKAGE_DIRECTORIES=
ROS_DISTRO=hydro
PYTHONPATH=/home/uss/cws_proof/install/lib/python2.7/dist-packages:/opt/ros/hydro/lib/python2.7/dist-packages
PKG_CONFIG_PATH=/home/uss/cws_proof/install/lib/pkgconfig:/opt/ros/hydro/lib/pkgconfig
CMAKE_PREFIX_PATH=/home/uss/cws_proof/install:/opt/ros/hydro
ROS_ETC_DIR=/opt/ros/hydro/etc/ros
$ ls -alth `find install -iname 'rtls*'`
-rw-rw-r-- 1 n130s n130s 9.5K Feb 13 22:17 install/lib/python2.7/dist-packages/rtshell/rtls.pyc
-rw-rw-r-- 1 n130s n130s  14K Feb  7  2011 install/lib/python2.7/dist-packages/rtshell/rtls.py
```

I guess `scripts` files need to be installed?
http://docs.ros.org/hydro/api/catkin/html/howto/installing_python.html

**Comment by k-okada** [comment]
sorry i commit the patch 97f81bc2b3bd1e9ba807421cabfeabce3be02590

**Comment by 130s** [comment]
>  i commit the patch 97f81bc

I added a comment [here](https://github.com/k-okada/rtshell_core/commit/97f81bc2b3bd1e9ba807421cabfeabce3be02590#commitcomment-5366343) (for some reason this commit is really hard to find from anywhere). I think it's good to merge at least from my perspective where `rosrun rtshell rtls` for debugging is in great need (now enabled with the patch I posted in the comment).

**Comment by k-okada** [comment]
Sorry I delete and roll back this pull request, since this is not working well. I'll announce if it is ready.

**Comment by k-okada** [comment]
I created different implementation as Pull #5. this should be ok. (of course,  we still have discussion of whre rtls installed), so continue discussion on Pull #5 thread.

**Pull request closed without merging**
